/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int res;
  int pkt = __VERIFIER_nondet_int();
  while (pkt < 10) {
    res = 0;
    while (res == 0) {
      res = __VERIFIER_nondet_int();
      pkt ++;
      if (res == 0) {
        
        
        break;
      }
    }
  }
  return;
}


