/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int num = 65535;
  int bytes = 1;
  while ((num + (unsigned int)1) >> bytes * 7) bytes ++;
  return;
}


