analysis.algorithm.termination = true
analysis.machineModel = Linux64
analysis.name = terminationAnalysis
analysis.programNames = /FILES_DIR/concretizer/Undefined_Behavior_1_Loop0_TestCase3.c
analysis.restartAfterUnknown = true
counterexample.export.exportWitness = false
cpa.arg.lateMerge = prevent
language = C
limits.time.cpu = 900s
log.level = INFO
output.path = /FILES_DIR/Undefined_Behavior_1_Loop0_TestCase3
parser.usePreprocessor = true
restartAlgorithm.configFiles = components/combinations-parallel-termination.properties, components/termination-recursion.properties::if-recursive
specification = 
statistics.print = true
