/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int nfds = 2;
  int nr = 200;
  int NR_OPEN = 100;
  while (nfds <= nr) {
    nfds *= 2;
    if (nfds > NR_OPEN) nfds = NR_OPEN;
  }
  return;
}


