/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int __retres;
  int reg_count = 1;
  if (reg_count > 65534) {
    __retres = 0;
    goto return_label;
  }
  while (reg_count) ;
  return_label: return;
}


