/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int gettablesize_slice_1(void)
{
  int __retres;
  int i = 90000;
  i %= 99999;
  if (i < 0) __retres = - i; else __retres = i;
  return __retres;
}

void main(void)
{
  long i;
  int tmp;
  tmp = gettablesize_slice_1();
  long max_fds = (long)tmp;
  i = (long)0;
  while (i < max_fds) i ++;
  return;
}


