/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int linesToRead = 2;
  if (linesToRead < 0) goto return_label;
  int h = 5;
  while (h > 0) {
    if (linesToRead > h) linesToRead = h;
    h -= linesToRead;
  }
  return_label: return;
}


