/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int flag = 0;
int ff_subtitles_next_line_slice_1(void)
{
  int __retres;
  int i = -3;
  i %= 1000;
  if (flag == 1) {
    __retres = 0;
    goto return_label;
  }
  if (i == 0) {
    flag = 1;
    __retres = 0;
  }
  else 
    if (i < 0) __retres = - i; else __retres = i;
  return_label: return __retres;
}

void main(void)
{
  int __retres;
  int b = 0;
  int end = 5;
  if (b < 0) {
    __retres = 0;
    goto return_label;
  }
  else 
    if (end < 0) {
      __retres = 0;
      goto return_label;
    }
  while (b < end) {
    int tmp_1;
    tmp_1 = ff_subtitles_next_line_slice_1();
    b += tmp_1;
    if (b >= end - 4) {
      
      __retres = 0;
      goto return_label;
    }
  }
  return_label: return;
}


