/* Generated by Frama-C */
#include "stdlib.h"
/*@ assigns \result;
    assigns \result \from \nothing; */
extern unsigned int __VERIFIER_nondet_uint(void);

int ffs_slice_1(unsigned int w)
{
  int i = 1;
  while (w % (unsigned int)2 == (unsigned int)0) {
    i ++;
    w /= (unsigned int)2;
  }
  return i;
}

void main(void)
{
  unsigned int w = __VERIFIER_nondet_uint();
  while (w != (unsigned int)0) {
    int n = ffs_slice_1(w);
    w >>= n;
  }
  return;
}


