/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int old_[10] = {9,0,0,0,0,0,0,0,0,0};
  int new_[10] = {8,0,0,0,0,0,0,0,0,0};
  {
    int j = 0;
    while (j < 9) {
      ;
      ;
      j ++;
    }
  }
  return;
}


