/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);


 __attribute__((__FC_BUILTIN__)) void __fc_vla_free(void *p);


 __attribute__((__FC_BUILTIN__)) void *__fc_vla_alloc(unsigned long size);

void main(void)
{
  int __retres;
  {
    unsigned long __lengthof_mcelog_entry;
    int MCE_LOG_LEN = 3;
    if (MCE_LOG_LEN <= 0) {
      __retres = 0;
      goto return_label;
    }
    else 
      if (MCE_LOG_LEN > 1000) {
        __retres = 0;
        goto return_label;
      }
    __lengthof_mcelog_entry = (unsigned long)MCE_LOG_LEN;
    int *mcelog_entry =
      __fc_vla_alloc(sizeof(int) * __lengthof_mcelog_entry);
    {
      int i = 0;
      while (i < MCE_LOG_LEN) {
        *(mcelog_entry + i) = __VERIFIER_nondet_int();
        i ++;
      }
    }
    int entry = 1;
    if (entry < 0) goto return_label;
    while (1) {
      if (entry >= MCE_LOG_LEN) {
        
        __retres = 0;
        __fc_vla_free((void *)mcelog_entry);
        goto return_label;
      }
      if (*(mcelog_entry + entry)) entry ++;
    }
  }
  return_label: return;
}


