/* Generated by Frama-C */
char *strchr_slice_1(char *str)
{
  char *__retres;
  
  __retres = str;
  goto return_label;
  return_label: return __retres;
}

void main(void)
{
  char in[100];
  {
    int i = 0;
    while (i < 99) {
      in[i] = (char)'\n';
      i ++;
    }
  }
  char *p = in;
  in[99] = (char)0;
  while (*p) {
    char *n = strchr_slice_1(p);
    p = n + 1;
  }
  return;
}


