/* Generated by Frama-C */

extern char __VERIFIER_nondet_char(void);

void main(void)
{
  char array[101] = "},terminating";
  int stop = 0;
  {
    int i = 0;
    while (i < 100) {
      ;
      i ++;
    }
  }
  array[100] = (char)0;
  char *p = array;
  while (1) {
    if (*p) {
      if (! (! stop)) break;
    }
    else break;
    switch ((int)*p) {
      case '}': stop = 1;
      
      break;
      case ':': ;
      if (*(p + 1)) 
        if ((int)*(p + 1) == '-') {
          p += 2;
          stop = 1;
        }
      
      break;
      default: p ++;
    }
  }
  return;
}


