/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int flag = 0;
int mdb_cursor_get_slice_1(void)
{
  int __retres;
  int i = 5;
  flag ++;
  if (flag > 1000) {
    __retres = 1;
    goto return_label;
  }
  if (i >= 0) __retres = 0; else __retres = 1;
  return_label: return __retres;
}

void main(void)
{
  int rc;
  rc = mdb_cursor_get_slice_1();
  int dval_mv_size = 10;
  while (rc == 0) {
    if (dval_mv_size <= 0) {
      rc = mdb_cursor_get_slice_1();
      continue;
    }
    rc = mdb_cursor_get_slice_1();
  }
  return;
}


