/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

int gtv_0;
void main(void)
{
  unsigned int val = 1;
  int bytes = 1;
  while (val >> (gtv_0 = bytes * 8)) bytes ++;
  return;
}


