/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int old_[10];
  int new_[10];
  {
    int j = 0;
    while (j < 9) {
      old_[j] = __VERIFIER_nondet_int();
      new_[j] = __VERIFIER_nondet_int();
      j ++;
    }
  }
  return;
}


