/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

unsigned int ffs_slice_1(unsigned int w)
{
  unsigned int i = (unsigned int)1;
  while (w % (unsigned int)2 == (unsigned int)0) {
    i ++;
    w /= (unsigned int)2;
  }
  return i;
}

void main(void)
{
  unsigned int w = 255;
  while (w != (unsigned int)0) {
    unsigned int n = ffs_slice_1(w);
    if (n < (unsigned int)32) w >>= n; else w = (unsigned int)0;
  }
  return;
}


