/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int i;
  int num = 100000;
  if (num > 65534) goto return_label;
  i = 0;
  while (i < num) {
    i = 0;
    while (i < 3) i ++;
    i ++;
  }
  return_label: return;
}


