/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int old_[10] = {1,1,1,1,1,1,1,1,1,1};
  int new_[10] = {2,2,2,2,2,2,2,2,2,2};
  {
    int j = 0;
    while (j < 9) {
      ;
      ;
      j ++;
    }
  }
  return;
}


