/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  int __retres;
  unsigned int pathlen = 1;
  unsigned int newbufsize = 16;
  unsigned int len = 4294967280;
  if (newbufsize == (unsigned int)0) {
    __retres = 0;
    goto return_label;
  }
  if ((newbufsize + len) + (unsigned int)1 == 0xffffffff) {
    __retres = 0;
    goto return_label;
  }
  while (newbufsize < (pathlen + len) + (unsigned int)1) newbufsize *= (unsigned int)2;
  return_label: return;
}


