/* Generated by Frama-C */

extern char __VERIFIER_nondet_char(void);

#define MEMORY0_SIZE 100000
char memory0[MEMORY0_SIZE];
int memory0_freeIndex = 1;
int allocate_memory0(int size) {
   int allocatedIndex = memory0_freeIndex;
   memory0_freeIndex = memory0_freeIndex + size;
   return allocatedIndex;
}

#define MEMORY1_SIZE 100000
char memory1[MEMORY1_SIZE];
int memory1_freeIndex = 1;
int allocate_memory1(int size) {
   int allocatedIndex = memory1_freeIndex;
   memory1_freeIndex = memory1_freeIndex + size;
   return allocatedIndex;
}

int strcspn_slice_1(int strSrc, int str)
{
  int __retres;
  int s;
  int t = strSrc;
  while ((int)memory1[t] != '\000') {
    s = str;
    while ((int)memory0[s] != '\000') {
      if ((int)memory1[t] == (int)memory0[s]) {
        
        
        __retres = (int)(t - strSrc);
        goto return_label;
      }
      s ++;
    }
    t ++;
  }
  __retres = 0;
  return_label: return __retres;
}

void main(void)
{
int newLine_index = allocate_memory0(2);
memory0[newLine_index + 0] = '\n';
memory0[newLine_index + 1] = '\0';
  int buf_index = allocate_memory1(100);
  {
    int i = 0;
    while (i < 99) {
      memory1[buf_index + (i)] = __VERIFIER_nondet_char();
      i ++;
    }
  }
  memory1[buf_index + (99)] = (char)'\000';
  int p = buf_index;
  while (memory1[p]) {
    int len = strcspn_slice_1(p,newLine_index);
    p += len;
    if (memory1[p]) p ++;
  }
  return;
}


