/* Generated by Frama-C */

extern char __VERIFIER_nondet_char(void);

void main(void)
{
  char buf[100];
  {
    int i = 0;
    while (i < 99) {
      buf[i] = __VERIFIER_nondet_char();
      i ++;
    }
  }
  return;
}


