#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */

extern long long __VERIFIER_nondet_int(void);

long long flag = 0;
long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
long long read_slice_1(long long loc, long long len)
{
  long long __retres;
  long long count = 0;
  while (loc < len) {
    long long num = 0;
    if (num == 0) {
      
      __retres = -1;
      goto return_label;
    }
    else {
      if (num < 0)
{ num = wrap_around(- num, INT_MIN, INT_MAX);
}
      num = wrap_around(num % (1000), INT_MIN, INT_MAX);
      (count = wrap_around(count + 1, INT_MIN, INT_MAX));
      if (num < 995)
{ (loc = wrap_around(loc + 1, INT_MIN, INT_MAX));
}
      else {
        
        __retres = count;
        goto return_label;
      }
    }
  }
  __retres = count;
  return_label: return __retres;
}

void main(void)
{
  long long ret;
  long long count = 5;
  if (count <= 0)
{ goto return_label;
}
  long long buf = 0;
  while (count > 0) {
    ret = read_slice_1(buf,count);
    if (ret < 0) {
      
      goto return_label;
    }
    count = wrap_around(count - (ret), INT_MIN, INT_MAX);
    buf = wrap_around(buf + (ret), INT_MIN, INT_MAX);
  }
  return_label: return;
}


