/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int slots_used[10] = {2,0,1,1,1,1,1,1,1,1};
  int ereg[10] = {0,1,1,1,1,1,1,1,1,1};
  {
    int i = 0;
    while (i < 10) {
      ;
      ;
      i ++;
    }
  }
  return;
}


