/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int old_[10] = {9,0,0,0,0,0,0,0,0,0};
  int new_[10] = {8,0,0,0,0,0,0,0,0,0};
  int i = 0;
  int base = 2;
  int count = 10;
  {
    int j = 0;
    while (j < 9) {
      ;
      ;
      j ++;
    }
  }
  old_[9] = 0;
  new_[9] = 0;
  while (1) {
    int number = base;
    while (old_[i] != new_[i]) {
      number ++;
      if (number == count) {
        
        
        goto done;
      }
    }
    i ++;
    base += 8;
  }
  done: ;
  return;
}


