/* Generated by Frama-C */

extern unsigned char __VERIFIER_nondet_uchar(void);


extern char __VERIFIER_nondet_char(void);

void main(void)
{
  unsigned char ac;
  unsigned char c1 = 255;
  char c2 = 0;
  ac = c1;
  while ((int)ac != (int)((unsigned char)c2)) ac = (unsigned char)((int)ac + 1);
  return;
}


