/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int ui = (unsigned int)1;
  unsigned int size = 100;
  unsigned int BUFFSIZE = 50;
  if (size < BUFFSIZE) size = BUFFSIZE;
  while (1) {
    if (ui < size) {
      if (! (ui * (unsigned int)2 > ui)) break;
    }
    else break;
    ui *= (unsigned int)2;
  }
  return;
}


