#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */

extern long long __VERIFIER_nondet_int(void);

long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
void main(void)
{
  long long __retres;
  long long reg_count = 70000;
  if (reg_count > 65534) {
    __retres = 0;
    goto return_label;
  }
  {
    long long i = 0;
    while (i < reg_count)
{ (i = wrap_around(i + 1, INT_MIN, INT_MAX));
}
  }
  return_label: return;
}


