/* Generated by Frama-C */

extern char __VERIFIER_nondet_char(void);

void main(void)
{
  char array[101] = ":0";
  {
    int i = 0;
    while (i < 100) {
      ;
      i ++;
    }
  }
  return;
}


