/* Generated by Frama-C */
#include "stdlib.h"
struct NNode {
   struct NNode *nxtact ;
};
typedef struct NNode INSDS;
INSDS *initLink(int n)
{
  int i;
  INSDS *head = malloc(sizeof(INSDS));
  i = 2;
  while (i <= n) i ++;
  return head;
}


