/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int num = 2147483648;
  num ++;
  while (1) {
    num >>= 7;
    if (! num) break;
  }
  return;
}


