/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int number = 2147483647;
  while (number >= (unsigned int)10) number /= (unsigned int)10;
  return;
}


