#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */

extern long long __VERIFIER_nondet_int(void);

long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
void main(void)
{
  long long i;
  long long num = __VERIFIER_nondet_int();
  if (num > 65534)
{ goto return_label;
}
  i = 0;
  while (i < num) {
    i = 0;
    while (i < 3)
{ (i = wrap_around(i + 1, INT_MIN, INT_MAX));
}
    (i = wrap_around(i + 1, INT_MIN, INT_MAX));
  }
  return_label: return;
}


