/* Generated by Frama-C */
#include "stdlib.h"
/*@ assigns \result;
    assigns \result \from \nothing; */
extern int __VERIFIER_nondet_int(void);

int flag = 0;
int read_slice_1(int loc, int len)
{
  int __retres;
  int count = 0;
  if (flag == 1) {
    __retres = 0;
    goto return_label;
  }
  while (loc < len) {
    int num = __VERIFIER_nondet_int();
    if (num == 0) {
      /*@ \slicing::slice_preserve_ctrl ; */ ;
      __retres = -1;
      goto return_label;
    }
    else {
      if (num < 0) num = - num;
      num %= 1000;
      count ++;
      if (num < 995) loc ++;
      else {
        flag = 1;
        /*@ \slicing::slice_preserve_ctrl ; */ ;
        __retres = count;
        goto return_label;
      }
    }
  }
  __retres = count;
  return_label: return __retres;
}

void main(void)
{
  int ret;
  int count = __VERIFIER_nondet_int();
  if (count <= 0) goto return_label;
  int buf = 0;
  int tries = 0;
  while (count > 0) {
    ret = read_slice_1(buf,count);
    if (ret <= 0) {
      if (ret == 0) {
        int tmp_0;
        tmp_0 = tries;
        tries ++;
        if (tmp_0 < 5) continue;
      }
      /*@ \slicing::slice_preserve_ctrl ; */ ;
      goto return_label;
    }
    count -= ret;
    buf += ret;
  }
  return_label: return;
}


