/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int __retres;
  int val = 1;
  if (val <= 0) {
    __retres = 0;
    goto return_label;
  }
  while (val != 0) val >>= 1;
  return_label: return;
}


