int __VERIFIER_nondet_int();
void main();
extern void __VERIFIER_error(void);
void main_0();
void main_0() {
  int i;
  int number = 2147483647;
  i = 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __CPROVER_assume(i <= number);
  i = i * 10;
  __VERIFIER_error(); // target state
}
