#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */

extern long long __VERIFIER_nondet_uint(void);

long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
void main(void)
{
  long long cur;
  long long best = 2;
  long long st_max = 4294967295;
  long long it_min = 0;
  if (st_max <= it_min)
{ goto return_label;
}
  if (best == (unsigned int)0)
{ goto return_label;
}
  cur = best;
  while (1) {
    if (st_max < cur) {
      
      break;
    }
    cur = wrap_around(cur + (best), 0, UINT_MAX);
  }
  return_label: return;
}


