#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */
long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
void main(void)
{
  long long div1;
  div1 = (unsigned int)1;
  if (! (div1 >= (unsigned int)0))
{ goto break_cont_1;
}
  break_cont_1: ;
  return;
}


