unsigned int __VERIFIER_nondet_uint();
void main();
extern void __VERIFIER_error(void);
void main_0();
void main_0() {
  unsigned int ui = 1U;
  unsigned int size = 4294967295L;
  unsigned int BUFFSIZE = 0;
  __CPROVER_assume(!(size < BUFFSIZE));
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __CPROVER_assume(ui < size);
  ui = ui * 2U;
  __VERIFIER_error(); // target state
}
