/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int __retres;
  int i;
  int num_crtc = 5;
  int num_output = 70000;
  if (num_crtc > 65534) goto return_label;
  else 
    if (num_output > 65534) {
      __retres = 0;
      goto return_label;
    }
  i = 0;
  while (i < num_crtc) {
    i = 0;
    while (i < num_output) i ++;
    i ++;
  }
  return_label: return;
}


