/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int flag = 0;
int read_slice_1(int loc, int len)
{
  int __retres;
  int count = 0;
  if (flag == 1) {
    __retres = 0;
    goto return_label;
  }
  while (loc < len) {
    int num = 500;
    if (num == 0) {
      
      __retres = -1;
      goto return_label;
    }
    else {
      if (num < 0) num = - num;
      num %= 1000;
      count ++;
      if (num < 995) loc ++;
      else {
        flag = 1;
        
        __retres = count;
        goto return_label;
      }
    }
  }
  __retres = count;
  return_label: return __retres;
}

void main(void)
{
  int __retres;
  int pos = 0;
  int size = 70000;
  flag = 0;
  int __fc_errno_0 = 0;
  if (size <= 0) {
    __retres = 0;
    goto return_label;
  }
  else 
    if (size > 65536) {
      __retres = 0;
      goto return_label;
    }
  while (pos < size) {
    int rc = read_slice_1(pos,size - pos);
    if (rc == -1) {
      __fc_errno_0 ++;
      if (__fc_errno_0 == 5) {
        
        goto return_label;
      }
      continue;
    }
    pos += rc;
  }
  return_label: return;
}


