unsigned int __VERIFIER_nondet_uint();
int main();
extern void __VERIFIER_error(void);
int main_0();
int main_0() {
  unsigned int pathlen = 4294967200L;
  unsigned int newbufsize = 95;
  unsigned int len = 4294967288L;
  __CPROVER_assume(!(newbufsize == 0));
  __CPROVER_assume(!(((newbufsize + len) + 1) == 4294967295U));
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __CPROVER_assume(newbufsize < ((pathlen + len) + 1));
  newbufsize = newbufsize * 2;
  __VERIFIER_error(); // target state
}
