/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int n = 500;
  while (n > (unsigned int)0) {
    unsigned int len = n;
    if (len > (unsigned int)16) len = (unsigned int)16;
    n -= len;
  }
  return;
}


