/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int flag = 0;
int fgetc_slice_1(void)
{
  int __retres;
  if (flag > 1000) {
    __retres = -1;
    goto return_label;
  }
  flag ++;
  int c = 511;
  if (c < 0) c = - c;
  c %= 256;
  __retres = c;
  return_label: return __retres;
}

void main(void)
{
  int temp;
  while (1) {
    temp = fgetc_slice_1();
    if (temp == '\000') goto _LOR;
    else 
      if (temp == -1) {
        _LOR: {
                
                goto return_label;
              }
      }
    switch (temp) {
      case -1: ;
      case '=': {
                  
                  break;
                }
      case '\000': {
                     
                     break;
                   }
      default: 
    }
  }
  return_label: return;
}


