#include <limits.h>
#include <stdint.h>
/* Generated by Frama-C */

extern long long __VERIFIER_nondet_int(void);

long long flag = 0;
long long wrap_around(long long value, long long lower_bound, long long upper_bound) {
    long long range = upper_bound - lower_bound + 1;
    if (value > upper_bound) {
        return lower_bound + (value - upper_bound - 1) % range;
    }
    else if (value < lower_bound) {
        return upper_bound - (lower_bound - value - 1) % range;
    }
    return value;
}
long long ff_subtitles_next_line_slice_1(void)
{
  long long __retres;
  long long i = 5;
  i = wrap_around(i % (1000), INT_MIN, INT_MAX);
  if (flag == 1) {
    __retres = 0;
    goto return_label;
  }
  if (i == 0) {
    flag = 1;
    __retres = 0;
  }
  else 
    if (i < 0)
{ __retres = wrap_around(- i, INT_MIN, INT_MAX);
} else __retres = i;
  return_label: return __retres;
}

void main(void)
{
  long long __retres;
  long long b = 10;
  long long end = 5;
  if (b < 0) {
    __retres = 0;
    goto return_label;
  }
  else 
    if (end < 0) {
      __retres = 0;
      goto return_label;
    }
  while (b < end) {
    long long tmp_1;
    tmp_1 = ff_subtitles_next_line_slice_1();
    b = wrap_around(b + (tmp_1), INT_MIN, INT_MAX);
    if (b >= wrap_around(end - 4, INT_MIN, INT_MAX)) {
      
      __retres = 0;
      goto return_label;
    }
  }
  return_label: return;
}


