/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int slots_used[10] = {2,1,1,1,1,1,1,1,1,1};
  int ereg[10] = {1,1,1,1,1,1,1,1,1,1};
  int table;
  int EVENT_EPOLL_TABLES = 10;
  {
    int i = 0;
    while (i < 10) {
      ;
      ;
      i ++;
    }
  }
  int i_0 = 0;
  while (i_0 < EVENT_EPOLL_TABLES) {
    switch (slots_used[i_0]) {
      case 2: continue;
      case 0:
      if (! ereg[i_0]) {
        
        goto return_label;
      }
      else table = ereg[i_0];
      
      break;
      default: table = ereg[i_0];
      
    }
    if (table) {
      
      break;
    }
    i_0 ++;
  }
  return_label: return;
}


