/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int ui = (unsigned int)1;
  unsigned int size = 4294967294;
  unsigned int BUFFSIZE = 10;
  if (size < BUFFSIZE) size = BUFFSIZE;
  while (ui < size) ui *= (unsigned int)2;
  return;
}


