/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int n = 16;
  while (n > (unsigned int)0) {
    unsigned int len = n;
    n -= (unsigned int)16;
  }
  return;
}


