/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int __retres;
  int max_msg_size = 1024;
  int buffer_read_offset = 900;
  int buffer_bytes_left = 0;
  if (max_msg_size < -1) goto return_label;
  else 
    if (buffer_read_offset <= 0) goto return_label;
    else 
      if (buffer_bytes_left < 0) {
        __retres = 0;
        goto return_label;
      }
  int size = 64;
  while (buffer_bytes_left < size / 2) {
    size *= 2;
    if (max_msg_size != -1) 
      if (size > max_msg_size) size = max_msg_size;
    buffer_bytes_left = size - buffer_read_offset;
  }
  return_label: return;
}


