analysis.algorithm.termination = true
analysis.machineModel = Linux64
analysis.name = terminationAnalysis
analysis.programNames = /FILES_DIR/concretizer/Adding_Subtracting_Zero_4_NT_Loop50_TestCase9.c
analysis.restartAfterUnknown = true
counterexample.export.exportWitness = false
cpa.arg.lateMerge = prevent
language = C
limits.time.cpu = 900s
log.level = INFO
output.path = /FILES_DIR/Adding_Subtracting_Zero_4_NT_Loop50_TestCase9
parser.usePreprocessor = true
restartAlgorithm.configFiles = components/combinations-parallel-termination.properties, components/termination-recursion.properties::if-recursive
specification = 
statistics.print = true
