/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

void main(void)
{
  int needed = 1073741824;
  int smallest = 1;
  while (smallest <= needed) {
    if (smallest == 0) goto return_label;
    smallest <<= 1;
  }
  return_label: return;
}


