/* Generated by Frama-C */

extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int cur;
  unsigned int best = 100;
  unsigned int st_max = 1000;
  unsigned int it_min = 10;
  if (st_max <= it_min) goto return_label;
  if (best == (unsigned int)0) goto return_label;
  cur = best;
  while (1) {
    if (st_max < cur) {
      
      break;
    }
    cur += best;
  }
  return_label: return;
}


