/* Generated by Frama-C */

extern int __VERIFIER_nondet_int(void);

int flag = 0;
int count = 0;
int read_slice_1(void)
{
  int __retres;
  if (flag == 1) {
    __retres = 0;
    goto return_label;
  }
  else 
    if (count > 100) {
      __retres = 0;
      goto return_label;
    }
  int num = -1;
  if (num <= 0) __retres = -1;
  else {
    num %= 1000;
    if (num < 995) {
      count ++;
      __retres = num;
    }
    else {
      flag = 1;
      __retres = 0;
    }
  }
  return_label: return __retres;
}

void main(void)
{
  while (1) {
    int tmp;
    tmp = read_slice_1();
    if (tmp <= 0) {
      
      break;
    }
  }
  return;
}


